version: "3.9"

services:
  api:
    build:
      context: .                 # ← เห็นทั้งโปรเจกต์
      dockerfile: ./api/Dockerfile
    container_name: wichayada-api-10783
    environment:
      - NODE_ENV=production
      - PORT=10783
      - DB_HOST=postgres
      - DB_PORT=20783
      - REDIS_HOST=redis
      - REDIS_PORT=30783
      - CORS_ORIGIN=*
    ports:
      - "10783:10783"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:10783/healthz"]
      interval: 10s
      timeout: 3s
      retries: 10

  postgres:
    image: postgres:16-alpine
    container_name: postgres-20783
    command: ["postgres", "-p", "20783"]
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppass
      - POSTGRES_DB=appdb
    ports:
      - "20783:20783"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -p 20783"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis-30783
    command: ["redis-server", "--port", "30783"]
    ports:
      - "30783:30783"
