version: '3.9'

services:

  # --- Nginx Reverse Proxy ---
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "10783:80"  # bind port 80 ของ container ไปที่ 10783 ของ host
    depends_on:
      - api
    restart: unless-stopped

  # --- Node.js API ---
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      NODE_ENV: 'production'
      PORT: '10783'
      DB_HOST: 'postgres'
      DB_PORT: '20783'
      POSTGRES_USER: 'appuser'
      POSTGRES_PASSWORD: 'apppass'
      POSTGRES_DB: 'appdb'
      REDIS_HOST: 'redis'
      REDIS_PORT: '30783'
      CORS_ORIGIN: 'http://10.80.29.16:10883'  # client IP
    volumes:
      - ./api:/usr/src/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  # --- PostgreSQL Database ---
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    command: ["postgres", "-p", "20783"]
    environment:
      POSTGRES_USER: 'appuser'
      POSTGRES_PASSWORD: 'apppass'
      POSTGRES_DB: 'appdb'
    ports:
      - "20783:20783"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -h 127.0.0.1 -p 20783 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s
    restart: unless-stopped

  # --- Redis Cache ---
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    command: ["redis-server", "--port", "30783"]
    ports:
      - "30783:30783"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
